"A datetime string with format `Y-m-d H:i:s`, e.g. `2018-05-23 13:45:32`."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

type Query {
    "Mengambil semua data verifikasi (Collection)"
    verifications: [Verification!]! @all

    "Mengambil satu data verifikasi berdasarkan user_id (Resource)"
    verification(user_id: ID @eq): Verification @find
}

type Verification {
    id: ID!
    user_id: Int!
    nik: String!
    bank_account_number: String!
    verification_status: String!
    created_at: DateTime!
    updated_at: DateTime!
}